version: 0.2

env:

  variables:
    
    AWS_DEFAULT_REGION: "eu-north-1"
    
phases:

  pre_build:

    commands:

      - echo Logging in to Amazon ECR...

      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 075577609825.dkr.ecr.eu-north-1.amazonaws.com

      - REPOSITORY_URI=075577609825.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/myweb
      
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      
      - IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
      
  build:

    commands:
    
      - echo Building the Docker image...
    
      - docker build -t $REPOSITORY_URI .
      
      - echo Tagging the Docker image...
      
      - docker tag $REPOSITORY_URI:latest $IMAGE_URI
      
  post_build:

    commands:

      - echo Pushing the Docker image to Amazon ECR...
      
      - docker push $IMAGE_URI
      
      - echo Writing image definitions file...
      
      - printf '[{"name":"myweb","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json
      
      - cat imagedefinitions.json


artifacts:
  files:
  
    - imagedefinitions.json
